apiVersion: v1
kind: Pod
metadata:
  name: test-virtualization
  labels:
    role: test-virtualization-role
spec:
  containers:
    - name: test-virtualization-container
      image: bambrikii/test-virtualization-image:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
